import { Command } from 'commander'

import { UsageError } from '../api/errors.js'

/**
 * Completion is generated by walking the live Commander tree rather than being
 * written out by hand, so a new command or flag is completable the moment it is
 * registered and there is no second list to forget to update.
 */
interface Node {
  /** Space-separated path below `skrybe`, e.g. "subscribers add". Empty at the root. */
  path: string
  /** Everything completable at this point: subcommands, aliases and long flags. */
  words: string[]
  description: string
}

const SHELLS = ['bash', 'zsh', 'fish'] as const
type Shell = (typeof SHELLS)[number]

function longFlags(command: Command): string[] {
  const flags = command.options.map((option) => option.long).filter((l): l is string => !!l)
  return [...flags, '--help']
}

/**
 * Values for arguments and options that take a fixed set, keyed by the path or
 * flag they belong to. There is no way to read these off Commander, and
 * completing `--output <tab>` to nothing is the kind of gap that makes people
 * stop reaching for tab.
 */
const CHOICES: Record<string, string[]> = {
  completion: ['bash', 'zsh', 'fish'],
}

export const FLAG_CHOICES: Record<string, string[]> = {
  '--output': ['table', 'json', 'text'],
}

/**
 * Depth-first walk, parents before children.
 *
 * `paths` carries every spelling that reaches this command, so an alias works
 * as a path segment rather than only appearing in the suggestions — otherwise
 * `skrybe subs <tab>` would silently fall back to the root command list.
 */
function collect(command: Command, paths: string[], into: Node[]): void {
  const children = command.commands
  const names = children.flatMap((child) => [child.name(), ...child.aliases()])

  for (const path of paths) {
    into.push({
      path,
      words: [...names, ...(CHOICES[path] ?? []), ...longFlags(command)],
      description: command.description(),
    })
  }

  for (const child of children) {
    const segments = [child.name(), ...child.aliases()]
    const childPaths = paths.flatMap((parent) =>
      segments.map((segment) => (parent === '' ? segment : `${parent} ${segment}`)),
    )
    collect(child, childPaths, into)
  }
}

/** Root options are accepted anywhere, so they are offered everywhere. */
function buildNodes(program: Command): Node[] {
  const nodes: Node[] = []
  collect(program, [''], nodes)

  const globals = longFlags(program)
  return nodes.map((node) =>
    node.path === ''
      ? node
      : { ...node, words: [...new Set([...node.words, ...globals])] },
  )
}

/** Emit a `case` arm per flag that takes a fixed set of values. */
function flagCases(indent: string, template: string): string {
  return Object.entries(FLAG_CHOICES)
    .map(([flag, values]) => `${indent}${flag}) ${template.replace('%s', values.join(' '))} ;;`)
    .join('\n')
}

function bash(nodes: Node[]): string {
  const cases = nodes
    .map((n) => `    ${n.path === '' ? '""' : `"${n.path}"`}) echo "${n.words.join(' ')}" ;;`)
    .join('\n')

  // The path is rebuilt by keeping only words that name a real command at the
  // point they appear, so an option's value — `--list l7763...` — is skipped
  // without the script needing to know which options take one.
  return `# skrybe bash completion. Add to ~/.bashrc:
#   eval "$(skrybe completion bash)"
_skrybe_words_for() {
  case "$1" in
${cases}
    *) echo "" ;;
  esac
}

_skrybe() {
  local cur prev path candidate word i
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  path=""

  case "$prev" in
${flagCases('    ', 'COMPREPLY=($(compgen -W "%s" -- "$cur")); return')}
  esac

  for ((i = 1; i < COMP_CWORD; i++)); do
    word="\${COMP_WORDS[i]}"
    case "$word" in -*) continue ;; esac
    candidate="\${path:+$path }$word"
    if [ -n "$(_skrybe_words_for "$candidate")" ]; then
      path="$candidate"
    fi
  done

  COMPREPLY=($(compgen -W "$(_skrybe_words_for "$path")" -- "$cur"))
}

complete -F _skrybe skrybe
`
}

function zsh(nodes: Node[]): string {
  const cases = nodes
    .map((n) => `    ${n.path === '' ? "''" : `'${n.path}'`}) echo "${n.words.join(' ')}" ;;`)
    .join('\n')

  return `#compdef skrybe
# skrybe zsh completion. Add to ~/.zshrc:
#   eval "$(skrybe completion zsh)"
_skrybe_words_for() {
  case "$1" in
${cases}
    *) echo "" ;;
  esac
}

_skrybe() {
  local prev path candidate word i
  path=""
  prev="\${words[CURRENT-1]}"

  case "$prev" in
${flagCases('    ', 'compadd -- %s; return')}
  esac

  # $words is 1-indexed and includes the command itself.
  for (( i = 2; i < CURRENT; i++ )); do
    word="\${words[i]}"
    case "$word" in -*) continue ;; esac
    candidate="\${path:+$path }$word"
    if [[ -n "$(_skrybe_words_for "$candidate")" ]]; then
      path="$candidate"
    fi
  done

  compadd -- \${=$(_skrybe_words_for "$path")}
}

# Sourcing this before compinit has run would fail with a bare
# "command not found: compdef", which reads like a broken script rather
# than a missing setup step.
if (( ! $+functions[compdef] )); then
  autoload -Uz compinit && compinit
fi

compdef _skrybe skrybe
`
}

/**
 * fish matches on subcommands seen anywhere in the line rather than on a path,
 * so this covers the two levels that exist — `skrybe subscribers add` — which
 * is the whole tree today.
 */
function fish(nodes: Node[], program: Command): string {
  const lines: string[] = [
    '# skrybe fish completion. Save as:',
    '#   skrybe completion fish > ~/.config/fish/completions/skrybe.fish',
    '',
    // No file completion: none of these commands take a path as a bare argument.
    'complete -c skrybe -f',
  ]

  const escape = (s: string): string => s.replace(/'/g, "\\'")

  for (const child of program.commands) {
    lines.push(
      `complete -c skrybe -n __fish_use_subcommand -a ${child.name()} -d '${escape(child.description())}'`,
    )
    for (const grandchild of child.commands) {
      lines.push(
        `complete -c skrybe -n "__fish_seen_subcommand_from ${child.name()}" -a ${grandchild.name()} -d '${escape(grandchild.description())}'`,
      )
    }
  }

  for (const node of nodes) {
    const condition =
      node.path === ''
        ? '__fish_use_subcommand'
        : `"__fish_seen_subcommand_from ${node.path.split(' ').pop() ?? ''}"`
    for (const flag of node.words.filter((w) => w.startsWith('--'))) {
      lines.push(`complete -c skrybe -n ${condition} -l ${flag.slice(2)}`)
    }
  }

  return `${lines.join('\n')}\n`
}

export function completionCommand(getProgram: () => Command): Command {
  return new Command('completion')
    .argument('<shell>', `Shell to generate for: ${SHELLS.join(', ')}`)
    .description('Print a shell completion script')
    .addHelpText(
      'after',
      `
Examples:
  eval "$(skrybe completion bash)"        # add to ~/.bashrc
  eval "$(skrybe completion zsh)"         # add to ~/.zshrc
  skrybe completion fish > ~/.config/fish/completions/skrybe.fish
`,
    )
    .action((shell: string) => {
      if (!SHELLS.includes(shell as Shell)) {
        throw new UsageError(
          `Cannot generate completion for "${shell}".`,
          `Supported shells: ${SHELLS.join(', ')}`,
        )
      }

      const program = getProgram()
      const nodes = buildNodes(program)
      const script =
        shell === 'bash' ? bash(nodes) : shell === 'zsh' ? zsh(nodes) : fish(nodes, program)

      process.stdout.write(script)
    })
}
